article_homepage:
    path:     /
    defaults: { _controller: ArticleBundle:Default:index }


article_panel:
    path:   /panel
    defaults: { _controller: ArticleBundle:Panel:panel }

article_add:
    path:     /panel/article/add
    defaults: { _controller: ArticleBundle:Panel:addArticle}

article_edit:
    path:   /panel/article/edit/{$slug}
    defaults: { _controller: ArticleBundle:Panel:editArticle }

article_myArticle:
    path: /panel/article/my
    defaults: { _controller: ArticleBundle:Panel:myArticleList }

article_allArticle:
    path: /articles/{page}
    defaults: { _controller: ArticleBundle:Default:listAllArticles, page:1 }

article_select:
    path:     /{slug}
    defaults: { _controller: ArticleBundle:Default:viewSelectArticle}
